"""phase2: supply chain (vehicles, orders, routes, deliveries)

Revision ID: 3f23ccfe6b5d
Revises: b3c88a0cbe88
Create Date: 2026-07-04 17:07:42.776928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import saig.shared.database  # custom column types (GUID, TZDateTime)


revision: str = '3f23ccfe6b5d'
down_revision: Union[str, None] = 'b3c88a0cbe88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('destination_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('created_by', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_orders_organization_id_organizations')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_orders_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('registration', sa.String(length=30), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('driver_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_vehicles_driver_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vehicles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('organization_id', 'registration', name='uq_vehicles_org_reg')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_organization_id'), ['organization_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('order_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('variety_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['seed_varieties.id'], name=op.f('fk_order_items_variety_id_seed_varieties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('route_plans',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('origin_warehouse_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('vehicle_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('driver_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('optimizer_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_route_plans_driver_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_route_plans_organization_id_organizations')),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], name=op.f('fk_route_plans_origin_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_route_plans_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_plans'))
    )
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_plans_status'), ['status'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('order_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('route_plan_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('delivered_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_deliveries_order_id_orders')),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], name=op.f('fk_deliveries_route_plan_id_route_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_status'), ['status'], unique=False)

    op.create_table('route_stops',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('route_plan_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('order_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('stop_sequence', sa.SmallInteger(), nullable=False),
    sa.Column('eta', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_route_stops_order_id_orders')),
    sa.ForeignKeyConstraint(['route_plan_id'], ['route_plans.id'], name=op.f('fk_route_stops_route_plan_id_route_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_plan_id', 'order_id', name='uq_route_stop_order'),
    sa.UniqueConstraint('route_plan_id', 'stop_sequence', name='uq_route_stop_seq')
    )
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_stops_route_plan_id'), ['route_plan_id'], unique=False)

    op.create_table('delivery_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('delivery_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('occurred_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_delivery_events_delivery_id_deliveries')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_delivery_events_recorded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_events'))
    )
    with op.batch_alter_table('delivery_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_events_delivery_id'), ['delivery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_events_delivery_id'))

    op.drop_table('delivery_events')
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_stops_route_plan_id'))

    op.drop_table('route_stops')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_deliveries_order_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_plans_status'))
        batch_op.drop_index(batch_op.f('ix_route_plans_organization_id'))

    op.drop_table('route_plans')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_organization_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_organization_id'))

    op.drop_table('orders')
    # ### end Alembic commands ###
