"""iam baseline: orgs, users, roles, permissions, tokens, audit

Revision ID: 4044d5ec3921
Revises: 
Create Date: 2026-07-02 13:13:08.416994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import saig.shared.database


revision: str = '4044d5ec3921'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_table', sa.String(length=80), nullable=True),
    sa.Column('entity_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('occurred_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_table', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('ux_organizations_slug', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('permissions',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('departments',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_departments_org_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_organization_id'), ['organization_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_org_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_organization_id'), ['organization_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('permission_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('department_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ux_users_email', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('password_reset_tokens',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('user_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('used_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('user_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('family_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('role_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ux_users_email', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_organization_id'))

    op.drop_table('roles')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_organization_id'))

    op.drop_table('departments')
    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('ux_organizations_slug', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('organizations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
