"""fieldops + catalog: regions, farmers, farms, fields, crop cycles, varieties

Revision ID: b2630ec2033c
Revises: 4044d5ec3921
Create Date: 2026-07-03 08:43:32.713635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import saig.shared.database  # custom column types (GUID, TZDateTime)  # noqa: F401


revision: str = 'b2630ec2033c'
down_revision: Union[str, None] = '4044d5ec3921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_regions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_regions_org_code')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_organization_id'), ['organization_id'], unique=False)

    op.create_table('seed_varieties',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('crop', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('maturity_days', sa.SmallInteger(), nullable=True),
    sa.Column('yield_potential_kg_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('drought_tolerance', sa.SmallInteger(), nullable=True),
    sa.Column('disease_tolerance', sa.SmallInteger(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_seed_varieties_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_varieties'))
    )
    with op.batch_alter_table('seed_varieties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seed_varieties_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ux_varieties_org_code', ['organization_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('variety_region_suitability',
    sa.Column('variety_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_variety_region_suitability_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['seed_varieties.id'], name=op.f('fk_variety_region_suitability_variety_id_seed_varieties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variety_id', 'region_id', name=op.f('pk_variety_region_suitability'))
    )
    op.create_table('farmers',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('cooperative', sa.String(length=200), nullable=True),
    sa.Column('consent_given_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('registered_by', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_farmers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_farmers_region_id_regions')),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], name=op.f('fk_farmers_registered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmers'))
    )
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ux_farmers_org_national_id', ['organization_id', 'national_id'], unique=True, postgresql_where=sa.text('national_id IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('national_id IS NOT NULL AND deleted_at IS NULL'))
        batch_op.create_index('ux_farmers_org_phone', ['organization_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))

    op.create_table('farms',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('farmer_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('total_area_ha', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farms_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_farms_organization_id_organizations')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_farms_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms'))
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index('ix_farms_lat_lng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_organization_id'), ['organization_id'], unique=False)

    op.create_table('production_records',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('farmer_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('season', sa.String(length=40), nullable=False),
    sa.Column('variety_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('yield_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_production_records_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['variety_id'], ['seed_varieties.id'], name=op.f('fk_production_records_variety_id_seed_varieties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_records')),
    sa.UniqueConstraint('farmer_id', 'season', 'variety_id', name='uq_production_farmer_season')
    )
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_records_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('farm_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_fields_farm_id_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields'))
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_farm_id'), ['farm_id'], unique=False)

    op.create_table('crop_cycles',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('field_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('variety_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('season', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('planted_at', sa.Date(), nullable=True),
    sa.Column('expected_harvest_at', sa.Date(), nullable=True),
    sa.Column('actual_harvest_at', sa.Date(), nullable=True),
    sa.Column('actual_yield_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('practices', sa.JSON(), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_crop_cycles_field_id_fields')),
    sa.ForeignKeyConstraint(['variety_id'], ['seed_varieties.id'], name=op.f('fk_crop_cycles_variety_id_seed_varieties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_cycles'))
    )
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_cycles_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_status'), ['status'], unique=False)

    op.create_table('soil_samples',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('field_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('sampled_at', sa.Date(), nullable=False),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('nitrogen_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('phosphorus_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassium_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('organic_matter_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('texture', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_soil_samples_field_id_fields')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soil_samples'))
    )
    with op.batch_alter_table('soil_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soil_samples_field_id'), ['field_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_samples_field_id'))

    op.drop_table('soil_samples')
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_field_id'))

    op.drop_table('crop_cycles')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_farm_id'))

    op.drop_table('fields')
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_records_farmer_id'))

    op.drop_table('production_records')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_organization_id'))
        batch_op.drop_index('ix_farms_lat_lng')
        batch_op.drop_index(batch_op.f('ix_farms_farmer_id'))

    op.drop_table('farms')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_index('ux_farmers_org_phone', postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index('ux_farmers_org_national_id', postgresql_where=sa.text('national_id IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('national_id IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_farmers_organization_id'))

    op.drop_table('farmers')
    op.drop_table('variety_region_suitability')
    with op.batch_alter_table('seed_varieties', schema=None) as batch_op:
        batch_op.drop_index('ux_varieties_org_code', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_seed_varieties_organization_id'))

    op.drop_table('seed_varieties')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_organization_id'))

    op.drop_table('regions')
    # ### end Alembic commands ###
