"""phase2: weather, crop health, inventory

Revision ID: b3c88a0cbe88
Revises: b2630ec2033c
Create Date: 2026-07-03 14:14:57.791120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import saig.shared.database  # custom column types (GUID, TZDateTime)


revision: str = 'b3c88a0cbe88'
down_revision: Union[str, None] = 'b2630ec2033c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_cells',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('cell_key', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_cells')),
    sa.UniqueConstraint('cell_key', name=op.f('uq_weather_cells_cell_key'))
    )
    op.create_table('diseases',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('crop', sa.String(length=60), nullable=False),
    sa.Column('pathogen_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment_guide', sa.Text(), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_diseases_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diseases'))
    )
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diseases_organization_id'), ['organization_id'], unique=False)

    op.create_table('weather_forecasts',
    sa.Column('cell_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('issued_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['weather_cells.id'], name=op.f('fk_weather_forecasts_cell_id_weather_cells')),
    sa.PrimaryKeyConstraint('cell_id', 'forecast_date', name=op.f('pk_weather_forecasts')),
    sa.UniqueConstraint('cell_id', 'forecast_date', name='uq_forecast_cell_date')
    )
    op.create_table('weather_observations',
    sa.Column('cell_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['weather_cells.id'], name=op.f('fk_weather_observations_cell_id_weather_cells')),
    sa.PrimaryKeyConstraint('cell_id', 'observed_date', name=op.f('pk_weather_observations'))
    )
    op.create_table('stock_lots',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('variety_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('lot_number', sa.String(length=60), nullable=False),
    sa.Column('produced_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('germination_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > produced_at', name=op.f('ck_stock_lots_lot_expiry_after_production')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_stock_lots_organization_id_organizations')),
    sa.ForeignKeyConstraint(['variety_id'], ['seed_varieties.id'], name=op.f('fk_stock_lots_variety_id_seed_varieties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_lots')),
    sa.UniqueConstraint('organization_id', 'lot_number', name='uq_lots_org_number')
    )
    with op.batch_alter_table('stock_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_lots_organization_id'), ['organization_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('manager_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_warehouses_manager_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_warehouses_organization_id_organizations')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_warehouses_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_warehouses_org_code')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_organization_id'), ['organization_id'], unique=False)

    op.create_table('stock_transfers',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('from_warehouse_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('to_warehouse_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('lot_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('requested_by', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('variance_note', sa.Text(), nullable=True),
    sa.Column('dispatched_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('received_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_warehouse_id <> to_warehouse_id', name=op.f('ck_stock_transfers_transfer_distinct_warehouses')),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_from_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['lot_id'], ['stock_lots.id'], name=op.f('fk_stock_transfers_lot_id_stock_lots')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_stock_transfers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_stock_transfers_requested_by_users')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_to_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers'))
    )
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_transfers_organization_id'), ['organization_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('lot_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('transfer_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('performed_by', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('occurred_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['stock_lots.id'], name=op.f('fk_stock_movements_lot_id_stock_lots')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_stock_movements_performed_by_users')),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('fk_stock_movements_transfer_id_stock_transfers')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_balance', ['warehouse_id', 'lot_id'], unique=False)

    op.create_table('disease_reports',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('crop_cycle_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('disease_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('reported_by', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('affected_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_outbreak', sa.Boolean(), nullable=False),
    sa.Column('reported_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', saig.shared.database.TZDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], name=op.f('fk_disease_reports_crop_cycle_id_crop_cycles')),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('fk_disease_reports_disease_id_diseases')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_disease_reports_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_disease_reports_reported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disease_reports'))
    )
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_reports_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_reports_status'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_crop_cycle_id'))

    op.drop_table('disease_reports')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_balance')

    op.drop_table('stock_movements')
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transfers_organization_id'))

    op.drop_table('stock_transfers')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_organization_id'))

    op.drop_table('warehouses')
    with op.batch_alter_table('stock_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_lots_organization_id'))

    op.drop_table('stock_lots')
    op.drop_table('weather_observations')
    op.drop_table('weather_forecasts')
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diseases_organization_id'))

    op.drop_table('diseases')
    op.drop_table('weather_cells')
    # ### end Alembic commands ###
