"""phase3: risk assessments

Revision ID: c79bdb10fa67
Revises: 20a0913c83fe
Create Date: 2026-07-05 14:41:42.391422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import saig.shared.database  # custom column types (GUID, TZDateTime)


revision: str = 'c79bdb10fa67'
down_revision: Union[str, None] = '20a0913c83fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('organization_id', saig.shared.database.GUID(length=36), nullable=False),
    sa.Column('region_id', saig.shared.database.GUID(length=36), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('assessed_date', sa.Date(), nullable=False),
    sa.Column('created_at', saig.shared.database.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_assessments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_risk_assessments_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments')),
    sa.UniqueConstraint('organization_id', 'region_id', 'domain', 'assessed_date', name='uq_risk_scope_domain_date')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_risk_trend', ['organization_id', 'domain', 'assessed_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_trend')
        batch_op.drop_index(batch_op.f('ix_risk_assessments_organization_id'))

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
